# Generated by Django 5.1.15 on 2026-04-03 10:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("real_name", models.CharField(blank=True, default="", max_length=50)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("wx_openid", models.CharField(blank=True, max_length=64, null=True, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("auditor", "审核员"),
                            ("user", "普通用户"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "鐢ㄦ埛",
                "verbose_name_plural": "鐢ㄦ埛",
                "db_table": "user",
                "db_table_comment": "用户表",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DetectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_no", models.CharField(max_length=32, unique=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[("image", "鍥剧墖"), ("video", "瑙嗛")],
                        max_length=10,
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_file", models.FileField(upload_to="seatbelt/%Y/%m/%d/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("running", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "澶辫触"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("total_frames", models.PositiveIntegerField(default=1)),
                ("processed_frames", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.BigIntegerField(blank=True, null=True)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("violation_count", models.PositiveIntegerField(default=0)),
                ("has_violation", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, default="", max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detect_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "检测任务",
                "verbose_name_plural": "检测任务",
                "db_table": "detect_task",
                "db_table_comment": "妫€娴嬩换鍔¤〃",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result_index", models.PositiveIntegerField(default=1)),
                ("frame_index", models.PositiveIntegerField(blank=True, null=True)),
                ("frame_time_ms", models.BigIntegerField(blank=True, null=True)),
                ("frame_file", models.CharField(blank=True, default="", max_length=255)),
                ("result_image", models.CharField(blank=True, default="", max_length=255)),
                ("image_width", models.PositiveIntegerField(default=0)),
                ("image_height", models.PositiveIntegerField(default=0)),
                ("object_count", models.PositiveIntegerField(default=0)),
                ("vehicle_count", models.PositiveIntegerField(default=0)),
                ("person_count", models.PositiveIntegerField(default=0)),
                ("plate_count", models.PositiveIntegerField(default=0)),
                ("violation_count", models.PositiveIntegerField(default=0)),
                ("has_violation", models.BooleanField(default=False)),
                ("max_confidence", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="seatbelt.detecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测结果",
                "verbose_name_plural": "检测结果",
                "db_table": "detect_result",
                "db_table_comment": "妫€娴嬬粨鏋滆〃",
                "ordering": ["result_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetectObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_index", models.PositiveIntegerField(default=1)),
                ("track_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("vehicle", "杞﹁締"),
                            ("person", "浜虹墿"),
                            ("seatbelt", "安全带"),
                            ("license_plate", "杞︾墝"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_label", models.CharField(max_length=50)),
                ("source_model", models.CharField(blank=True, default="", max_length=50)),
                ("confidence", models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ("bbox_xmin", models.IntegerField()),
                ("bbox_ymin", models.IntegerField()),
                ("bbox_xmax", models.IntegerField()),
                ("bbox_ymax", models.IntegerField()),
                ("crop_data", models.BinaryField(blank=True, null=True)),
                ("crop_content_type", models.CharField(default="image/jpeg", max_length=100)),
                ("plate_text", models.CharField(blank=True, default="", max_length=32)),
                ("plate_score", models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ("seatbelt_status", models.CharField(blank=True, default="", max_length=20)),
                ("is_violation", models.BooleanField(default=False)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "parent_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="seatbelt.detectobject",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detect_objects",
                        to="seatbelt.detectresult",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detect_objects",
                        to="seatbelt.detecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "检测目标",
                "verbose_name_plural": "检测目标",
                "db_table": "detect_object",
                "db_table_comment": "妫€娴嬬洰鏍囨槑缁嗚〃",
                "ordering": ["object_index", "id"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_type", models.CharField(max_length=50)),
                ("target_type", models.CharField(blank=True, default="", max_length=50)),
                ("target_id", models.BigIntegerField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, default="")),
                ("request_method", models.CharField(blank=True, default="", max_length=10)),
                ("request_path", models.CharField(blank=True, default="", max_length=255)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "鎿嶄綔鏃ュ織",
                "verbose_name_plural": "鎿嶄綔鏃ュ織",
                "db_table": "operation_log",
                "db_table_comment": "操作日志表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_module", models.CharField(max_length=50)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("result_count", models.IntegerField(default=0)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="query_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "鏌ヨ鏃ュ織",
                "verbose_name_plural": "鏌ヨ鏃ュ織",
                "db_table": "query_log",
                "db_table_comment": "查询日志表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ViolationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("violation_no", models.CharField(max_length=32, unique=True)),
                (
                    "violation_type",
                    models.CharField(
                        choices=[("no_seatbelt", "未系安全带")],
                        default="no_seatbelt",
                        max_length=30,
                    ),
                ),
                ("plate_text", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "检测完成"),
                            (1, "申请待审核"),
                            (2, "申请审核通过"),
                            (3, "申请审核驳回"),
                        ],
                        default=0,
                    ),
                ),
                ("audit_time", models.DateTimeField(blank=True, null=True)),
                ("audit_remark", models.CharField(blank=True, default="", max_length=500)),
                ("handled_time", models.DateTimeField(blank=True, null=True)),
                ("handled_remark", models.CharField(blank=True, default="", max_length=500)),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audited_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="seatbelt.detectobject",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="seatbelt.detectresult",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="seatbelt.detecttask",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "杩濊璁板綍",
                "verbose_name_plural": "杩濊璁板綍",
                "db_table": "violation_record",
                "db_table_comment": "违规记录表",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="idx_user_role"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="idx_user_created_at"),
        ),
        migrations.AddIndex(
            model_name="detecttask",
            index=models.Index(fields=["user", "status", "created_at"], name="idx_task_user_status_ct"),
        ),
        migrations.AddIndex(
            model_name="detecttask",
            index=models.Index(fields=["task_type", "status", "created_at"], name="idx_task_type_status_ct"),
        ),
        migrations.AddIndex(
            model_name="detecttask",
            index=models.Index(fields=["has_violation", "created_at"], name="idx_task_violation_ct"),
        ),
        migrations.AddIndex(
            model_name="detectresult",
            index=models.Index(fields=["task", "frame_index"], name="idx_result_task_frame"),
        ),
        migrations.AddIndex(
            model_name="detectresult",
            index=models.Index(fields=["has_violation", "created_at"], name="idx_result_violation_ct"),
        ),
        migrations.AddConstraint(
            model_name="detectresult",
            constraint=models.UniqueConstraint(fields=("task", "result_index"), name="uk_task_result_index"),
        ),
        migrations.AddIndex(
            model_name="detectobject",
            index=models.Index(fields=["result", "object_type"], name="idx_object_result_type"),
        ),
        migrations.AddIndex(
            model_name="detectobject",
            index=models.Index(fields=["result", "is_violation"], name="idx_object_result_vio"),
        ),
        migrations.AddIndex(
            model_name="detectobject",
            index=models.Index(fields=["parent_object"], name="idx_object_parent"),
        ),
        migrations.AddIndex(
            model_name="detectobject",
            index=models.Index(fields=["track_id"], name="idx_object_track"),
        ),
        migrations.AddIndex(
            model_name="detectobject",
            index=models.Index(fields=["plate_text"], name="idx_object_plate_text"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["user", "created_at"], name="idx_operation_user_ct"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["target_type", "target_id"], name="idx_operation_target"),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(fields=["operation_type", "created_at"], name="idx_operation_type_ct"),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(fields=["user", "created_at"], name="idx_query_user_ct"),
        ),
        migrations.AddIndex(
            model_name="querylog",
            index=models.Index(fields=["query_module", "created_at"], name="idx_query_module_ct"),
        ),
        migrations.AddIndex(
            model_name="violationrecord",
            index=models.Index(fields=["status", "created_at"], name="idx_violation_status_ct"),
        ),
        migrations.AddIndex(
            model_name="violationrecord",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="idx_violation_user_status_ct",
            ),
        ),
        migrations.AddIndex(
            model_name="violationrecord",
            index=models.Index(fields=["plate_text", "status"], name="idx_violation_plate_status"),
        ),
        migrations.AddIndex(
            model_name="violationrecord",
            index=models.Index(fields=["auditor", "audit_time"], name="idx_violation_auditor_time"),
        ),
    ]
