# Generated by Django 5.1.15 on 2026-04-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_daily_detection_stats(apps, schema_editor):
    DetectTask = apps.get_model("seatbelt", "DetectTask")
    DailyDetectionStat = apps.get_model("seatbelt", "DailyDetectionStat")

    counts = {}
    tasks = DetectTask.objects.filter(status="completed", user_id__isnull=False).only("user_id", "created_at", "finished_at")
    for task in tasks.iterator():
        stat_time = task.finished_at or task.created_at
        if stat_time is None:
            continue

        stat_date = timezone.localtime(stat_time).date() if timezone.is_aware(stat_time) else stat_time.date()
        key = (task.user_id, stat_date)
        counts[key] = counts.get(key, 0) + 1

    DailyDetectionStat.objects.bulk_create(
        [
            DailyDetectionStat(user_id=user_id, stat_date=stat_date, detection_count=detection_count)
            for (user_id, stat_date), detection_count in counts.items()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("seatbelt", "0003_remove_user_real_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDetectionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stat_date", models.DateField()),
                ("detection_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_detection_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily detection stat",
                "verbose_name_plural": "Daily detection stats",
                "db_table": "daily_detection_stat",
                "db_table_comment": "每日检测统计表",
                "ordering": ["-stat_date", "user_id"],
            },
        ),
        migrations.AddIndex(
            model_name="dailydetectionstat",
            index=models.Index(fields=["stat_date"], name="idx_daily_stat_date"),
        ),
        migrations.AddIndex(
            model_name="dailydetectionstat",
            index=models.Index(fields=["user", "stat_date"], name="idx_daily_stat_user_date"),
        ),
        migrations.AddConstraint(
            model_name="dailydetectionstat",
            constraint=models.UniqueConstraint(
                fields=("user", "stat_date"),
                name="uk_daily_detection_stat_user_date",
            ),
        ),
        migrations.RunPython(backfill_daily_detection_stats, migrations.RunPython.noop),
    ]
