from django.urls import path

from .views import (
    change_password_view,
    dashboard_view,
    detection_detail,
    detection_list_create,
    health_check,
    login_view,
    miniapp_login_view,
    miniapp_bind_phone_view,
    miniapp_me_view,
    miniapp_plate_delete,
    miniapp_plate_list_create,
    miniapp_register_view,
    miniapp_violation_detail,
    miniapp_violation_list,
    miniapp_violation_review,
    miniapp_wx_login_view,
    logout_view,
    me_view,
    object_image,
    operation_log_list,
    query_log_list,
    refresh_token_view,
    register_view,
    user_detail_update,
    user_list_create,
    user_reset_password,
    violation_detail,
    violation_list,
    violation_review,
)


urlpatterns = [
    path("health/", health_check, name="seatbelt-health"),
    path("dashboard/", dashboard_view, name="seatbelt-dashboard"),
    path("auth/register/", register_view, name="seatbelt-register"),
    path("auth/login/", login_view, name="seatbelt-login"),
    path("auth/refresh/", refresh_token_view, name="seatbelt-refresh"),
    path("auth/logout/", logout_view, name="seatbelt-logout"),
    path("auth/me/", me_view, name="seatbelt-me"),
    path("auth/change-password/", change_password_view, name="seatbelt-change-password"),
    path("miniapp/auth/register/", miniapp_register_view, name="seatbelt-miniapp-register"),
    path("miniapp/auth/login/", miniapp_login_view, name="seatbelt-miniapp-login"),
    path("miniapp/auth/wx-login/", miniapp_wx_login_view, name="seatbelt-miniapp-wx-login"),
    path("miniapp/auth/bind-phone/", miniapp_bind_phone_view, name="seatbelt-miniapp-bind-phone"),
    path("miniapp/me/", miniapp_me_view, name="seatbelt-miniapp-me"),
    path("miniapp/plates/", miniapp_plate_list_create, name="seatbelt-miniapp-plate-list"),
    path("miniapp/plates/<int:binding_id>/", miniapp_plate_delete, name="seatbelt-miniapp-plate-delete"),
    path("miniapp/violations/", miniapp_violation_list, name="seatbelt-miniapp-violation-list"),
    path("miniapp/violations/<int:violation_id>/", miniapp_violation_detail, name="seatbelt-miniapp-violation-detail"),
    path("miniapp/violations/<int:violation_id>/review/", miniapp_violation_review, name="seatbelt-miniapp-violation-review"),
    path("detections/", detection_list_create, name="seatbelt-detection-list"),
    path("detections/<int:record_id>/", detection_detail, name="seatbelt-detection-detail"),
    path("violations/", violation_list, name="seatbelt-violation-list"),
    path("violations/<int:violation_id>/", violation_detail, name="seatbelt-violation-detail"),
    path("violations/<int:violation_id>/review/", violation_review, name="seatbelt-violation-review"),
    path("logs/query/", query_log_list, name="seatbelt-query-log-list"),
    path("logs/operation/", operation_log_list, name="seatbelt-operation-log-list"),
    path("system/users/", user_list_create, name="seatbelt-user-list"),
    path("system/users/<int:user_id>/", user_detail_update, name="seatbelt-user-detail"),
    path("system/users/<int:user_id>/reset-password/", user_reset_password, name="seatbelt-user-reset-password"),
    path("objects/<int:object_id>/image/", object_image, name="seatbelt-object-image"),
]
